// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ifd8S-mJcyANhXcxR42DNazN6Umm1XY',
    appId: '1:547515044678:web:66bb40da4195dbeebd8b47',
    messagingSenderId: '547515044678',
    projectId: 'allfirebaseauth-80627',
    authDomain: 'allfirebaseauth-80627.firebaseapp.com',
    storageBucket: 'allfirebaseauth-80627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVQ2KTvdKcHMGeWiQXUyxSuCbdcc2lnUw',
    appId: '1:547515044678:android:23868e5d0886c2e6bd8b47',
    messagingSenderId: '547515044678',
    projectId: 'allfirebaseauth-80627',
    storageBucket: 'allfirebaseauth-80627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3s5ckGH70Ecbks7AGl7E0Tu3y__7UE0',
    appId: '1:547515044678:ios:6e86d8188fe2099dbd8b47',
    messagingSenderId: '547515044678',
    projectId: 'allfirebaseauth-80627',
    storageBucket: 'allfirebaseauth-80627.appspot.com',
    iosClientId: '547515044678-piet4r3ve1drg7rckk5jt3aj7fuja6r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.allfirebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa3s5ckGH70Ecbks7AGl7E0Tu3y__7UE0',
    appId: '1:547515044678:ios:76d052114459f44abd8b47',
    messagingSenderId: '547515044678',
    projectId: 'allfirebaseauth-80627',
    storageBucket: 'allfirebaseauth-80627.appspot.com',
    iosClientId: '547515044678-4355s798j99pf9m9t4l84864m9d6m2ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.allfirebaseauth.RunnerTests',
  );
}
